# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-es-adapter'
    static_configs:
      - targets: ['192.168.99.1:8080']

remote_write:
  - url: http://192.168.99.1:8080/write

remote_read:
  - url: http://192.168.99.1:8080/read
